FROM node:10.14-alpine 

RUN apk --no-cache add rsync

ENV HOME /var/www/frontend
WORKDIR $HOME

COPY $PWD/code/package.json $HOME

RUN npm install

COPY $PWD/code $HOME

RUN npm run build -- --prod

COPY $PWD/entrypoint.prod.sh /usr/local

ENTRYPOINT ["sh", "/usr/local/entrypoint.prod.sh"]
