version: '3.5'

services:
  frontend:
    expose:
      - '4200'
    build:
      context: frontend
      dockerfile: Dockerfile
    working_dir: /var/www/frontend
    command: yarn start
    restart: always

  backend:
    expose:
      - '3000'
    build:
      context: backend
      dockerfile: Dockerfile
    working_dir: /usr/local/api

  mariadb:
    ports:
      - '13306:3306'

  nginx:
    ports:
      - '80:80'
    volumes:
      - ./nginx/cors.conf:/etc/nginx/vhost.d/default_location
      - ./nginx/sites-enabled/dev.conf:/etc/nginx/conf.d/dev.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
