version: '3.5'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    volumes:
      - frontend-dist:/usr/share/frontend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    expose:
      - '3000'

  nginx:
    ports:
      - '80:80'
    volumes:
      - frontend-dist:/var/www/frontend
      - ./nginx/cors.conf:/etc/nginx/vhost.d/default_location
      - ./nginx/sites-enabled/prod.conf:/etc/nginx/conf.d/prod.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  frontend-dist:
